
line-length = 100
[format]
exclude = [
    ".git",
    ".venv",
    ".history",
    "build",
    "dist",
    "docs",
    "hack",
]
quote-style = "preserve"
[lint]
select = [
    # More stuff here https://docs.astral.sh/ruff/rules/
    "F", # Pyflakes
    "E", # Pycodestyle Error
    "W", # Pycodestyle Warning
    "N", # PEP8 Naming
    # TODO "UP", # Pyupgrade
    # TODO "ANN",
    # TODO "S", # Bandit
    # "B", # Bugbear
    "A", # flake-8-builtins
    "YTT", # flake-8-2020
    "PLC", # Pylint Convention
    "PLE", # Pylint Error
    "PLW", # Pylint Warning
]
# Some checks should be enabled for code sanity disabled now
# to avoid changing too many lines
ignore = [
    "F821", # TODO Undefined name
    # Some Exceptions such as NotFound and NotFoundError can be ambiguous
    # This change need to be performed with carefulness
    "N818", # TODO Error Suffix in exception name
    # This can lead to API breaking changes so it's disabled for now
    "N80", # TODO Invalid Name
]
[lint.per-file-ignores]
"podman/tests/*.py" = ["S"]
[lint.flake8-builtins]
builtins-ignorelist = ["copyright", "all"]
